config/routes.rb
MapsExample::Application.routes.draw do

  root "maps#index"
  resources :maps

end

app/models/map.rb
class Map < ActiveRecord::Base
  geocoded_by :address do |object, results|
    if results.present?
      object.latitude = results.first.latitude
      object.longitude = results.first.longitude
    else
      object.latitude = nil
      object.longitude = nil
    end
  end

  before_validation :geocode, if: :address_changed?

  validates :address, presence: true
  validates :title, presence: true
  validate :found_address_presence

  def found_address_presence
    if latitude.blank? || longitude.blank?
      errors.add(:address, ": We couldn't find the address in google maps")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  def index
    @maps = Map.where.not(latitude: nil, longitude: nil).order('created_at DESC')
    @hash = Gmaps4rails.build_markers(@maps) do |map, marker|
      marker.lat map.latitude
      marker.lng map.longitude
      marker.infowindow render_to_string(partial: "/maps/map_box", locals: { map: map })
    end
  end

  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  def show
    @map = Map.find(params[:id])
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    if @map.update(map_params)
      redirect_to @map, notice: 'Map was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def create
    @map = Map.new(map_params)
    if @map.save
      flash[:success] = "Map place added!"
      redirect_to root_path
    else
      render action: 'new'
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_map
    @map = Map.find(params[:id])
  end

  def map_params
    params.require(:map).permit(:title, :address, :visited_by)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dynamic Google Maps</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid">
    <%= yield %>
  </div>

  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_SERVER_API_KEY"]}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

  <%= javascript_include_tag "application" %>

  <%= yield(:after_js) %>
</body>
</html>

app/views/maps/_form.html.erb
<div class="row-fluid">
  <div class="col-md-4 col-md-offset-4">
    <div class="row">


      <h1>Create/Edit your map</h1>
      <%= form_for(@map) do |f| %>
          <% if @map.errors.any? %>
              <div id="error_explanation" class="alert">
                <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

                <ul>
                  <% @map.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.submit "GO", class: "btn btn-primary" %>
          </div>
      <% end %>


    </div>
  </div>

</div>

app/views/maps/_map.html.erb
<li>
  <%= link_to map.title, map_path(map) %>
</li>

app/views/maps/_map_box.html.erb
<div class="map_box">
  <h3><%= map.title %></h3>
  <p><%= map.address %></p>
  <%= link_to "Details", map_path(map), target: :blank, class: "btn btn-warning" %>
</div>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<div class="row-fluid">
  <div class="col-md-6">
    <h2> Dynamic Google Maps </h2>
    <div id="map" style='width: 100%; height: 600px;'></div>
  </div>
  <div class="col-md-6">
    <%= link_to new_map_path do %>
        <button class="btn btn-primary">Add Map</button>
    <% end %>

    <hr>
    <% @maps.each do |map| %>
        <div class="row-fluid col-md-6">
          <h2><%= link_to map.title, map %></h2>
          <p><%= map.address %></p>
          <p>Latitude: <%= map.latitude %></p>
          <p>Longitude: <%= map.longitude %></p>
          <%= link_to "Edit", edit_map_path(map), class: "btn btn-default" %>
          or
          <%= link_to "delete", map, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default"  %>
        </div>
    <% end %>
  </div>
</div>

<% content_for(:after_js) do %>
    <script type="text/javascript">
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function(){
            markers = handler.addMarkers(<%= raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            if (markers.length == 0) {
                handler.getMap().setZoom(2);
            } else if (markers.length == 1) {
                handler.getMap().setZoom(14);
            }
        });
    </script>
<% end %>

app/views/maps/new.html.erb
<header><h1 class="display-4">Add Place to the Map</h1></header>

<%= render 'form' %>

app/views/maps/show.html.erb
<header><h1 class="display-4"><%= @map.title %></h1></header>

<p>Address: <%= @map.address %></p>
<p>Coordinates: <%= @map.latitude %> <%= @map.longitude %></p>
<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@map.latitude},#{@map.longitude}&markers=#{@map.latitude},#{@map.longitude}&zoom=7&size=640x400&key=#{ENV["GOOGLE_SERVER_API_KEY"]}",
              class: 'img-fluid img-rounded', alt: "#{@map.title} on the map"%>